

-- 
--
--
-- Ada.Containers
-- │
-- ├── Vectors
-- ├── Doubly_Linked_Lists
-- ├── Indefinite_Vectors
-- ├── Indefinite_Doubly_Linked_Lists
-- │
-- ├── Hashed_Maps
-- ├── Ordered_Maps
-- ├── Indefinite_Hashed_Maps
-- ├── Indefinite_Ordered_Maps
-- │
-- ├── Hashed_Sets
-- ├── Ordered_Sets
-- ├── Indefinite_Hashed_Sets
-- ├── Indefinite_Ordered_Sets
-- │
-- ├── Multiway_Trees
-- └── Indefinite_Multiway_Trees
-- 
--
--
